### ISSUE TITLE
Failed to detect Firefox

### ISSUE THREAD

**Issue by stonecrusher** [rzander/ruckzuck#78]
Win10x64
RuckZuck v1.7.1.3
Firefox 71.0x64

![2019-12-08_RuckZuck](https://user-images.githubusercontent.com/1388389/70395924-2cadcb00-1a04-11ea-937c-cf1f4b3451f7.png)

Seems like an issue with unclosed brackets?

/edit
Also undetected:
- Github Desktop
- XAMPP
- Signal
- Thunderbird
- Nitro Pro
- Scribus
- .NET and .NET35 (?)
- KeePass
- K-LiteCodecPack
- CDBurnerXP
- f.lux
- TeamViewer

Note that this list is based on looking through the "Install Software" list for items (not) marked green.

**Comment by rzander** [comment]
Thanks for reporting !

When RuckZuck detects installed SW, it will not run the detection script as it would take too long.. it just matches ProductName, Manufacturer and ProductVersion.  Only if you trigger an Installation, it will first check by script if the SW is installed...

I've fixed some of your reported Issues but for some I need more details:
- FireFox: **Fixed** Issue with Brackets.  ProductName = "Mozilla Firefox 71.0 (x64)" but you have "Mozilla Firefox 71.0 (x64 de)". Thats because the Firefox package will install FF based on yor Language Settings... (By Design)
- GithHub Desktop: Manufacturer = "GitHub, Inc." but RuckZuck has "GitHub, Inc" as it can not have a dot as last character (By Design)
- XAMPP >No Issue detected. What ProductName, Manufacturer and Version do you have ? Version contains invalid character so a compare may not work...
- Signal -> **Fixed:** ProductName has changed
- Thunderbird -> same as FF, its Language dependent
- Nitro Pro ->No Issue detected. What ProductName, Manufacturer and Version do you have ?
- Scribus ->No Issue detected. What ProductName, Manufacturer and Version do you have ?
- .NET and .NET35 (?) -> .NET35 is not registerred in AddRemove Programs, its a Windows Feature (By Design)
- KeePass ->No Issue detected. What ProductName, Manufacturer and Version do you have ?
- K-LiteCodecPack ->No Issue detected. What ProductName, Manufacturer and Version do you have ? Note: RZ has only the "Basic" Version of K-LiteCodecPack.. ?!
- CDBurnerXP -> No Issue detected. What ProductName, Manufacturer and Version do you have ?
- f.lux -> No Issue detected. What ProductName, Manufacturer and Version do you have ?
- TeamViewer -> **Fixed:** ProductName has changed

**Comment by rzander** [comment]
implemented Fixes :
https://github.com/rzander/ruckzuck/commit/2670262453be56f48d13cfea57826c79f7d3c6ec (will be part of V1.7.1.4)
https://github.com/rzander/ruckzuck/commit/6d6b2ae06b5aaddf484b6bc4d99ce4166dde2609 (Server already updated)

**Comment by stonecrusher** [comment]
Thank you for the fast reply and fix!

> ProductName, Manufacturer and ProductVersion

Not sure where to look them up. Is it the same as `DisplayName`, `Publisher` and `DisplayVersion` in the registry?

- XAMPP Control Panel v.3.2.4 compiled June 05th 2019: Probably local issue. Seems not properly installed as it doesn't show up in the Windows uninstall panel. But works fine. It maybe is a portable version or just copied from another PC. I don't know the version of the installer (current is 7.3.12).
- Nitro Pro: DisplayName `Nitro Pro`, Publisher `Nitro`, DisplayVersion `13.2.2.25` at  
`Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{A6827141-6E99-4CB7-BF18-90F805F802A8}`
- Scribus: DisplayName `Scribus 1.5.5 (64bit)`, Publisher `The Scribus Team`, DisplayVersion `1.5.5` at  
`Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Scribus 1.5.5`
- KeePass: DisplayName `KeePass Password Safe 2.43`, Publisher `Dominik Reichl`, DisplayVersion `2.43` at  
`Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\KeePassPasswordSafe2_is1`
- K-LiteCodecPack: DisplayName `K-Lite Codec Pack 15.2.6 Standard`, Publisher `KLCP`, DisplayVersion `15.2.6` at  
`Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\KLiteCodecPack_is1`  
--> Standard version, not "Basic".
- CDBurnerXP: DisplayName `CDBurnerXP`, Publisher `CDBurnerXP`, DisplayVersion `4.5.8.7128` at  
`Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{7E265513-8CDA-4631-B696-F40D983F3B07}_is1`
- f.lux: DisplayName `f.lux`, Publisher `f.lux Software LLC`, DisplayVersion doesn't show anything. Taken from "Programs and features" control panel (couldn't find it in the registry).

**Comment by rzander** [comment]
Yes these Keys are helpful... Thanks.
- Nitro Pro: If I enter these keys, RZ detects a new version ! Do you get an update as well ?
- Scribus: You have a newer Version than RZ as you are using the "Development Candidates" and not the "Stable branch"
- KeePass: Version in RZ is ```2.43.0```. This item will not marked green as the version does not match but you will get updates (if a new version exists)
- K-LiteCodecPac: DisplayName does not match. It will detect Updates but not sure if you can downgrade a Standard Version to a Basic Version... ?
- CDBurnerXP: RZ has ```Canneverbe Limited``` as Publisher.  It will not mark green but you will get updates as I  have fixed the detection method to also include ```CDBurnerXP``` as Publisher
- f.lux: No Version = no detection. If you install/update it with RZ, it will use the FileVersion as DisplayVersion.

I could fix some, but for the rest it's clear (to me) why these are not having a green(installed) Status.

**Comment by stonecrusher** [comment]
- Nitro Pro: Got update after I reset the update exclusions ✔️ 
- Scribus: That version was advertised like the "fresh" branch in LibreOffice and I can confirm it is very stable. However now it is clear why not "installed".
- KeePass: Not a real issue if I still get updates.
- K-Lite Codec Pack: Completely uninstalling and reinstalling from RuckZuck should do it.
- CDBurnerXP: Well, that's how it was set up by the official installer. Probably solved after updating next time with RuckZuck.
- f.lux: I don't know why they don't provide a version number. I probably have to reinstall to prevent f.lux updating itself rather than being updated via RuckZuck.
